//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viewer.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %localappdata%/Viewer/cache.db.
        /// </summary>
        internal static string CacheFilePath {
            get {
                return ResourceManager.GetString("CacheFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source={0};Version=3;Pooling=True;foreign keys=true.
        /// </summary>
        internal static string SqliteConnectionString {
            get {
                return ResourceManager.GetString("SqliteConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///CREATE TABLE IF NOT EXISTS `files` (
        ///	`id`	INTEGER NOT NULL,
        ///	`path`	TEXT NOT NULL UNIQUE COLLATE INVARIANT_CULTURE_IGNORE_CASE,
        ///	`lastWriteTime`	TEXT NOT NULL,
        ///	`lastAccessTime`	TEXT NOT NULL,
        ///	PRIMARY KEY(`id`)
        ///);
        ///CREATE TABLE IF NOT EXISTS `attributes` (
        ///	`id`	INTEGER NOT NULL,
        ///	`name`	TEXT NOT NULL COLLATE INVARIANT_CULTURE,
        ///	`source`	INTEGER NOT NULL DEFAULT 0,
        ///	`type`	INTEGER NOT NULL DEFAULT 0,
        ///	`value`	BLOB NOT NULL,
        ///	`owner`	INTEGER NOT NULL,
        ///	PRIMARY KEY(`id`),
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqliteInitializationScript {
            get {
                return ResourceManager.GetString("SqliteInitializationScript", resourceCulture);
            }
        }
    }
}
