//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Attribute Name.
        /// </summary>
        internal static string AttributeNameEmpty_Label {
            get {
                return ResourceManager.GetString("AttributeNameEmpty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name must not be empty.
        /// </summary>
        internal static string AttributeNameEmpty_Message {
            get {
                return ResourceManager.GetString("AttributeNameEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ConfirmDelete_Label {
            get {
                return ResourceManager.GetString("ConfirmDelete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete {0}?.
        /// </summary>
        internal static string ConfirmDelete_Message {
            get {
                return ResourceManager.GetString("ConfirmDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} files will be permanently deleted. Do you want to continue?.
        /// </summary>
        internal static string ConfirmDeleteAll_Message {
            get {
                return ResourceManager.GetString("ConfirmDeleteAll_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files.
        /// </summary>
        internal static string CopyingFiles_Label {
            get {
                return ResourceManager.GetString("CopyingFiles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultThumbnail {
            get {
                object obj = ResourceManager.GetObject("DefaultThumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Directory {
            get {
                object obj = ResourceManager.GetObject("Directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Found.
        /// </summary>
        internal static string DirectoryNotFound_Label {
            get {
                return ResourceManager.GetString("DirectoryNotFound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} was not found..
        /// </summary>
        internal static string DirectoryNotFound_Message {
            get {
                return ResourceManager.GetString("DirectoryNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DirectoryThumbnail {
            get {
                object obj = ResourceManager.GetObject("DirectoryThumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute name.
        /// </summary>
        internal static string DuplicateAttributeName_Label {
            get {
                return ResourceManager.GetString("DuplicateAttributeName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute name: {0}.
        /// </summary>
        internal static string DuplicateAttributeName_Message {
            get {
                return ResourceManager.GetString("DuplicateAttributeName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /select,&quot;{0}&quot;.
        /// </summary>
        internal static string ExplorerOpenFolderArguments {
            get {
                return ResourceManager.GetString("ExplorerOpenFolderArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string ExplorerProcessName {
            get {
                return ResourceManager.GetString("ExplorerProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        internal static string ExplorerWindowName {
            get {
                return ResourceManager.GetString("ExplorerWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Move.
        /// </summary>
        internal static string FailedToMove_Label {
            get {
                return ResourceManager.GetString("FailedToMove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to move {0} to {1}. 
        ///
        ///{0} was not found or {1} aready exists..
        /// </summary>
        internal static string FailedToMove_Message {
            get {
                return ResourceManager.GetString("FailedToMove_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File In Use.
        /// </summary>
        internal static string FileInUse_Label {
            get {
                return ResourceManager.GetString("FileInUse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is open in another application..
        /// </summary>
        internal static string FileInUse_Message {
            get {
                return ResourceManager.GetString("FileInUse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFound_Label {
            get {
                return ResourceManager.GetString("FileNotFound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found..
        /// </summary>
        internal static string FileNotFound_Message {
            get {
                return ResourceManager.GetString("FileNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Name.
        /// </summary>
        internal static string InvalidFileName_Label {
            get {
                return ResourceManager.GetString("InvalidFileName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid file name. File name must not be empty and it must not contain characters: {1}.
        /// </summary>
        internal static string InvalidFileName_Message {
            get {
                return ResourceManager.GetString("InvalidFileName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        internal static string ItemCount_Label {
            get {
                return ResourceManager.GetString("ItemCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftArrowIcon {
            get {
                object obj = ResourceManager.GetObject("LeftArrowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MessageIcon {
            get {
                object obj = ResourceManager.GetObject("MessageIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long..
        /// </summary>
        internal static string PathTooLong_Label {
            get {
                return ResourceManager.GetString("PathTooLong_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is too long:
        ///
        ///{0}.
        /// </summary>
        internal static string PathTooLong_Message {
            get {
                return ResourceManager.GetString("PathTooLong_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseIcon {
            get {
                object obj = ResourceManager.GetObject("PauseIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayIcon {
            get {
                object obj = ResourceManager.GetObject("PlayIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% complete.
        /// </summary>
        internal static string Progress_Label {
            get {
                return ResourceManager.GetString("Progress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query result.
        /// </summary>
        internal static string QueryResultWindowName {
            get {
                return ResourceManager.GetString("QueryResultWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightArrowIcon {
            get {
                object obj = ResourceManager.GetObject("RightArrowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Start {
            get {
                object obj = ResourceManager.GetObject("Start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        internal static string UnauthorizedAccess_Label {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access: {0}.
        /// </summary>
        internal static string UnauthorizedAccess_Message {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WarningIcon {
            get {
                object obj = ResourceManager.GetObject("WarningIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
