//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\projects\Viewer\Viewer\Query\Query.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Viewer.Query {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class QueryLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, SELECT=4, WHERE=5, ORDERBY=6, DIRECTION=7, PATH_PATTERN=8, 
		ID=9, INT=10, REAL=11, ADD_SUB=12, MULT_DIV=13, REL_OP=14, WS=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "SELECT", "WHERE", "ORDERBY", "DIRECTION", "PATH_PATTERN", 
		"ID", "INT", "REAL", "ADD_SUB", "MULT_DIV", "REL_OP", "WS"
	};


	public QueryLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QueryLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "','", "'SELECT'", "'WHERE'", "'ORDER BY'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "SELECT", "WHERE", "ORDERBY", "DIRECTION", "PATH_PATTERN", 
		"ID", "INT", "REAL", "ADD_SUB", "MULT_DIV", "REL_OP", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Query.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QueryLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '{', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x45', '\n', '\b', 
		'\x3', '\t', '\x3', '\t', '\x6', '\t', 'I', '\n', '\t', '\r', '\t', '\xE', 
		'\t', 'J', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\a', '\n', 
		'Q', '\n', '\n', '\f', '\n', '\xE', '\n', 'T', '\v', '\n', '\x3', '\v', 
		'\x6', '\v', 'W', '\n', '\v', '\r', '\v', '\xE', '\v', 'X', '\x3', '\f', 
		'\x6', '\f', '\\', '\n', '\f', '\r', '\f', '\xE', '\f', ']', '\x3', '\f', 
		'\x3', '\f', '\x6', '\f', '\x62', '\n', '\f', '\r', '\f', '\xE', '\f', 
		'\x63', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 's', '\n', '\xF', 
		'\x3', '\x10', '\x6', '\x10', 'v', '\n', '\x10', '\r', '\x10', '\xE', 
		'\x10', 'w', '\x3', '\x10', '\x3', '\x10', '\x2', '\x2', '\x11', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '\x3', '\x2', '\t', 
		'\x5', '\x2', '\f', '\f', '\xF', '\xF', '$', '$', '\x5', '\x2', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x4', '\x2', 
		'-', '-', '/', '/', '\x4', '\x2', ',', ',', '\x31', '\x31', '\x5', '\x2', 
		'\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x86', '\x2', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x3', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '#', '\x3', '\x2', '\x2', '\x2', '\a', '%', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\'', '\x3', '\x2', '\x2', '\x2', '\v', '.', '\x3', '\x2', 
		'\x2', '\x2', '\r', '\x34', '\x3', '\x2', '\x2', '\x2', '\xF', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x11', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'\x13', 'N', '\x3', '\x2', '\x2', '\x2', '\x15', 'V', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '[', '\x3', '\x2', '\x2', '\x2', '\x19', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', 'g', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'r', '\x3', '\x2', '\x2', '\x2', '\x1F', 'u', '\x3', '\x2', '\x2', '\x2', 
		'!', '\"', '\a', '*', '\x2', '\x2', '\"', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '#', '$', '\a', '+', '\x2', '\x2', '$', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\a', '.', '\x2', '\x2', '&', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\'', '(', '\a', 'U', '\x2', '\x2', '(', ')', '\a', 'G', '\x2', 
		'\x2', ')', '*', '\a', 'N', '\x2', '\x2', '*', '+', '\a', 'G', '\x2', 
		'\x2', '+', ',', '\a', '\x45', '\x2', '\x2', ',', '-', '\a', 'V', '\x2', 
		'\x2', '-', '\n', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 'Y', '\x2', 
		'\x2', '/', '\x30', '\a', 'J', '\x2', '\x2', '\x30', '\x31', '\a', 'G', 
		'\x2', '\x2', '\x31', '\x32', '\a', 'T', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'G', '\x2', '\x2', '\x33', '\f', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'Q', '\x2', '\x2', '\x35', '\x36', '\a', 'T', '\x2', '\x2', 
		'\x36', '\x37', '\a', '\x46', '\x2', '\x2', '\x37', '\x38', '\a', 'G', 
		'\x2', '\x2', '\x38', '\x39', '\a', 'T', '\x2', '\x2', '\x39', ':', '\a', 
		'\"', '\x2', '\x2', ':', ';', '\a', '\x44', '\x2', '\x2', ';', '<', '\a', 
		'[', '\x2', '\x2', '<', '\xE', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', 
		'\x46', '\x2', '\x2', '>', '?', '\a', 'G', '\x2', '\x2', '?', '@', '\a', 
		'U', '\x2', '\x2', '@', '\x45', '\a', '\x45', '\x2', '\x2', '\x41', '\x42', 
		'\a', '\x43', '\x2', '\x2', '\x42', '\x43', '\a', 'U', '\x2', '\x2', '\x43', 
		'\x45', '\a', '\x45', '\x2', '\x2', '\x44', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x44', '\x41', '\x3', '\x2', '\x2', '\x2', '\x45', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x46', 'H', '\a', '$', '\x2', '\x2', 'G', 'I', '\n', 
		'\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', 
		'$', '\x2', '\x2', 'M', '\x12', '\x3', '\x2', '\x2', '\x2', 'N', 'R', 
		'\t', '\x3', '\x2', '\x2', 'O', 'Q', '\t', '\x4', '\x2', '\x2', 'P', 'O', 
		'\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 'R', 
		'P', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 
		'S', '\x14', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'W', '\t', '\x5', '\x2', '\x2', 'V', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '\\', '\t', '\x5', '\x2', '\x2', '[', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', 
		'\x2', '\x2', '\x2', '_', '\x61', '\a', '\x30', '\x2', '\x2', '`', '\x62', 
		'\t', '\x5', '\x2', '\x2', '\x61', '`', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\t', '\x6', '\x2', '\x2', '\x66', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\t', '\a', '\x2', '\x2', 
		'h', '\x1C', '\x3', '\x2', '\x2', '\x2', 'i', 's', '\a', '?', '\x2', '\x2', 
		'j', 'k', '\a', '#', '\x2', '\x2', 'k', 's', '\a', '?', '\x2', '\x2', 
		'l', 's', '\a', '>', '\x2', '\x2', 'm', 'n', '\a', '>', '\x2', '\x2', 
		'n', 's', '\a', '?', '\x2', '\x2', 'o', 's', '\a', '@', '\x2', '\x2', 
		'p', 'q', '\a', '@', '\x2', '\x2', 'q', 's', '\a', '?', '\x2', '\x2', 
		'r', 'i', '\x3', '\x2', '\x2', '\x2', 'r', 'j', '\x3', '\x2', '\x2', '\x2', 
		'r', 'l', '\x3', '\x2', '\x2', '\x2', 'r', 'm', '\x3', '\x2', '\x2', '\x2', 
		'r', 'o', '\x3', '\x2', '\x2', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 
		's', '\x1E', '\x3', '\x2', '\x2', '\x2', 't', 'v', '\t', '\b', '\x2', 
		'\x2', 'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\b', '\x10', '\x2', 
		'\x2', 'z', ' ', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', '\x44', 'J', 
		'R', 'X', ']', '\x63', 'r', 'w', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Viewer.Query
