//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\projects\Viewer\Viewer\Query\Query.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Viewer.Query {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class QueryLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, SELECT=4, WHERE=5, ORDERBY=6, DIRECTION=7, ID=8, 
		INT=9, REAL=10, STRING=11, ADD_SUB=12, MULT_DIV=13, REL_OP=14, WS=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "SELECT", "WHERE", "ORDERBY", "DIRECTION", "ID", 
		"INT", "REAL", "STRING", "ADD_SUB", "MULT_DIV", "REL_OP", "WS"
	};


	public QueryLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public QueryLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "','", "'SELECT'", "'WHERE'", "'ORDER BY'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "SELECT", "WHERE", "ORDERBY", "DIRECTION", "ID", 
		"INT", "REAL", "STRING", "ADD_SUB", "MULT_DIV", "REL_OP", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Query.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QueryLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '|', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', '\x45', '\n', '\b', 
		'\x3', '\t', '\x3', '\t', '\a', '\t', 'I', '\n', '\t', '\f', '\t', '\xE', 
		'\t', 'L', '\v', '\t', '\x3', '\n', '\x6', '\n', 'O', '\n', '\n', '\r', 
		'\n', '\xE', '\n', 'P', '\x3', '\v', '\x6', '\v', 'T', '\n', '\v', '\r', 
		'\v', '\xE', '\v', 'U', '\x3', '\v', '\x3', '\v', '\x6', '\v', 'Z', '\n', 
		'\v', '\r', '\v', '\xE', '\v', '[', '\x3', '\f', '\x3', '\f', '\a', '\f', 
		'`', '\n', '\f', '\f', '\f', '\xE', '\f', '\x63', '\v', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 't', '\n', 
		'\xF', '\x3', '\x10', '\x6', '\x10', 'w', '\n', '\x10', '\r', '\x10', 
		'\xE', '\x10', 'x', '\x3', '\x10', '\x3', '\x10', '\x2', '\x2', '\x11', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '\x3', '\x2', 
		'\t', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\x3', '\x2', '$', '$', '\x4', '\x2', '-', '-', '/', 
		'/', '\x4', '\x2', ',', ',', '\x31', '\x31', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x2', '\x87', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '!', '\x3', '\x2', '\x2', '\x2', '\x5', '#', '\x3', 
		'\x2', '\x2', '\x2', '\a', '%', '\x3', '\x2', '\x2', '\x2', '\t', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\v', '.', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xF', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\x46', '\x3', '\x2', '\x2', '\x2', '\x13', 'N', '\x3', 
		'\x2', '\x2', '\x2', '\x15', 'S', '\x3', '\x2', '\x2', '\x2', '\x17', 
		']', '\x3', '\x2', '\x2', '\x2', '\x19', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x1B', 'h', '\x3', '\x2', '\x2', '\x2', '\x1D', 's', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', 'v', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\a', 
		'*', '\x2', '\x2', '\"', '\x4', '\x3', '\x2', '\x2', '\x2', '#', '$', 
		'\a', '+', '\x2', '\x2', '$', '\x6', '\x3', '\x2', '\x2', '\x2', '%', 
		'&', '\a', '.', '\x2', '\x2', '&', '\b', '\x3', '\x2', '\x2', '\x2', '\'', 
		'(', '\a', 'U', '\x2', '\x2', '(', ')', '\a', 'G', '\x2', '\x2', ')', 
		'*', '\a', 'N', '\x2', '\x2', '*', '+', '\a', 'G', '\x2', '\x2', '+', 
		',', '\a', '\x45', '\x2', '\x2', ',', '-', '\a', 'V', '\x2', '\x2', '-', 
		'\n', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', 'Y', '\x2', '\x2', '/', 
		'\x30', '\a', 'J', '\x2', '\x2', '\x30', '\x31', '\a', 'G', '\x2', '\x2', 
		'\x31', '\x32', '\a', 'T', '\x2', '\x2', '\x32', '\x33', '\a', 'G', '\x2', 
		'\x2', '\x33', '\f', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\a', 
		'Q', '\x2', '\x2', '\x35', '\x36', '\a', 'T', '\x2', '\x2', '\x36', '\x37', 
		'\a', '\x46', '\x2', '\x2', '\x37', '\x38', '\a', 'G', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'T', '\x2', '\x2', '\x39', ':', '\a', '\"', '\x2', '\x2', 
		':', ';', '\a', '\x44', '\x2', '\x2', ';', '<', '\a', '[', '\x2', '\x2', 
		'<', '\xE', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '\x46', '\x2', 
		'\x2', '>', '?', '\a', 'G', '\x2', '\x2', '?', '@', '\a', 'U', '\x2', 
		'\x2', '@', '\x45', '\a', '\x45', '\x2', '\x2', '\x41', '\x42', '\a', 
		'\x43', '\x2', '\x2', '\x42', '\x43', '\a', 'U', '\x2', '\x2', '\x43', 
		'\x45', '\a', '\x45', '\x2', '\x2', '\x44', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x44', '\x41', '\x3', '\x2', '\x2', '\x2', '\x45', '\x10', '\x3', 
		'\x2', '\x2', '\x2', '\x46', 'J', '\t', '\x2', '\x2', '\x2', 'G', 'I', 
		'\t', '\x3', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 
		'L', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 'M', 'O', '\t', '\x4', '\x2', 
		'\x2', 'N', 'M', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'P', 'N', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'Q', '\x14', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\t', '\x4', 
		'\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'Y', '\a', '\x30', 
		'\x2', '\x2', 'X', 'Z', '\t', '\x4', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '\x16', '\x3', 
		'\x2', '\x2', '\x2', ']', '\x61', '\a', '$', '\x2', '\x2', '^', '`', '\n', 
		'\x5', '\x2', '\x2', '_', '^', '\x3', '\x2', '\x2', '\x2', '`', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x62', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x61', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', 
		'$', '\x2', '\x2', '\x65', '\x18', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'g', '\t', '\x6', '\x2', '\x2', 'g', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\t', '\a', '\x2', '\x2', 'i', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'j', 't', '\a', '?', '\x2', '\x2', 'k', 'l', '\a', '#', '\x2', 
		'\x2', 'l', 't', '\a', '?', '\x2', '\x2', 'm', 't', '\a', '>', '\x2', 
		'\x2', 'n', 'o', '\a', '>', '\x2', '\x2', 'o', 't', '\a', '?', '\x2', 
		'\x2', 'p', 't', '\a', '@', '\x2', '\x2', 'q', 'r', '\a', '@', '\x2', 
		'\x2', 'r', 't', '\a', '?', '\x2', '\x2', 's', 'j', '\x3', '\x2', '\x2', 
		'\x2', 's', 'k', '\x3', '\x2', '\x2', '\x2', 's', 'm', '\x3', '\x2', '\x2', 
		'\x2', 's', 'n', '\x3', '\x2', '\x2', '\x2', 's', 'p', '\x3', '\x2', '\x2', 
		'\x2', 's', 'q', '\x3', '\x2', '\x2', '\x2', 't', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'w', '\t', '\b', '\x2', '\x2', 'v', 'u', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', 
		'\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', 
		'\x2', '\x2', 'z', '{', '\b', '\x10', '\x2', '\x2', '{', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x2', '\x44', 'J', 'P', 'U', '[', '\x61', 's', 'x', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Viewer.Query
