//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viewer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viewer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Label {
            get {
                return ResourceManager.GetString("About_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Attribute Name.
        /// </summary>
        public static string AttributeNameEmpty_Label {
            get {
                return ResourceManager.GetString("AttributeNameEmpty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute name must not be empty.
        /// </summary>
        public static string AttributeNameEmpty_Message {
            get {
                return ResourceManager.GetString("AttributeNameEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes_label {
            get {
                return ResourceManager.GetString("Attributes_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Busy.
        /// </summary>
        public static string ClipboardIsBusy_Label {
            get {
                return ResourceManager.GetString("ClipboardIsBusy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System clipboard cannot be opened. Try again later. System error: {0}.
        /// </summary>
        public static string ClipboardIsBusy_Message {
            get {
                return ResourceManager.GetString("ClipboardIsBusy_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete_Label {
            get {
                return ResourceManager.GetString("ConfirmDelete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete:
        ///{0}.
        /// </summary>
        public static string ConfirmDelete_Message {
            get {
                return ResourceManager.GetString("ConfirmDelete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} files will be permanently deleted. Do you want to continue?.
        /// </summary>
        public static string ConfirmDeleteAll_Message {
            get {
                return ResourceManager.GetString("ConfirmDeleteAll_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace file.
        /// </summary>
        public static string ConfirmReplace_Label {
            get {
                return ResourceManager.GetString("ConfirmReplace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already exists. Do you want to replace it?.
        /// </summary>
        public static string ConfirmReplace_Message {
            get {
                return ResourceManager.GetString("ConfirmReplace_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying files.
        /// </summary>
        public static string CopyingFiles_Label {
            get {
                return ResourceManager.GetString("CopyingFiles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Not Found.
        /// </summary>
        public static string DirectoryNotFound_Label {
            get {
                return ResourceManager.GetString("DirectoryNotFound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} was not found..
        /// </summary>
        public static string DirectoryNotFound_Message {
            get {
                return ResourceManager.GetString("DirectoryNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation_Label {
            get {
                return ResourceManager.GetString("Documentation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        public static string Done_Label {
            get {
                return ResourceManager.GetString("Done_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute name.
        /// </summary>
        public static string DuplicateAttributeName_Label {
            get {
                return ResourceManager.GetString("DuplicateAttributeName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate attribute name: {0}.
        /// </summary>
        public static string DuplicateAttributeName_Message {
            get {
                return ResourceManager.GetString("DuplicateAttributeName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty_Label {
            get {
                return ResourceManager.GetString("Empty_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string ErrorList_Label {
            get {
                return ResourceManager.GetString("ErrorList_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer.
        /// </summary>
        public static string ExplorerWindowName {
            get {
                return ResourceManager.GetString("ExplorerWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Move.
        /// </summary>
        public static string FailedToMove_Label {
            get {
                return ResourceManager.GetString("FailedToMove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to move {0} to {1}. 
        ///
        ///{0} was not found or {1} aready exists..
        /// </summary>
        public static string FailedToMove_Message {
            get {
                return ResourceManager.GetString("FailedToMove_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Open File.
        /// </summary>
        public static string FailedToOpenFile_Label {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///could not be opened. 
        ///
        ///{1} 
        ///
        ///Do you want to try again?.
        /// </summary>
        public static string FailedToOpenFile_Message {
            get {
                return ResourceManager.GetString("FailedToOpenFile_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File_Label {
            get {
                return ResourceManager.GetString("File_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File In Use.
        /// </summary>
        public static string FileInUse_Label {
            get {
                return ResourceManager.GetString("FileInUse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is open in another application..
        /// </summary>
        public static string FileInUse_Message {
            get {
                return ResourceManager.GetString("FileInUse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFound_Label {
            get {
                return ResourceManager.GetString("FileNotFound_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} was not found..
        /// </summary>
        public static string FileNotFound_Message {
            get {
                return ResourceManager.GetString("FileNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1:N0}).
        /// </summary>
        public static string Group_Label {
            get {
                return ResourceManager.GetString("Group_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help_Label {
            get {
                return ResourceManager.GetString("Help_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Name.
        /// </summary>
        public static string InvalidFileName_Label {
            get {
                return ResourceManager.GetString("InvalidFileName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid file name. File name must not be empty and it must not contain characters: {1}.
        /// </summary>
        public static string InvalidFileName_Message {
            get {
                return ResourceManager.GetString("InvalidFileName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must not be empty..
        /// </summary>
        public static string InvalidPath_Empty_Message {
            get {
                return ResourceManager.GetString("InvalidPath_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Path.
        /// </summary>
        public static string InvalidPath_Label {
            get {
                return ResourceManager.GetString("InvalidPath_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid path..
        /// </summary>
        public static string InvalidPath_Message {
            get {
                return ResourceManager.GetString("InvalidPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string ItemCount_Label {
            get {
                return ResourceManager.GetString("ItemCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Loading_Label {
            get {
                return ResourceManager.GetString("Loading_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0}: {1}.
        /// </summary>
        public static string Loading_Message {
            get {
                return ResourceManager.GetString("Loading_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUTTON4.
        /// </summary>
        public static string MouseButton4_Label {
            get {
                return ResourceManager.GetString("MouseButton4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUTTON5.
        /// </summary>
        public static string MouseButton5_Label {
            get {
                return ResourceManager.GetString("MouseButton5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too long..
        /// </summary>
        public static string PathTooLong_Label {
            get {
                return ResourceManager.GetString("PathTooLong_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is too long:
        ///
        ///{0}.
        /// </summary>
        public static string PathTooLong_Message {
            get {
                return ResourceManager.GetString("PathTooLong_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos_Label {
            get {
                return ResourceManager.GetString("Photos_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation.
        /// </summary>
        public static string Presentation_Label {
            get {
                return ResourceManager.GetString("Presentation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string PresentationPosition_Label {
            get {
                return ResourceManager.GetString("PresentationPosition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}%).
        /// </summary>
        public static string Progess_Title {
            get {
                return ResourceManager.GetString("Progess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% complete ({1} / {2}).
        /// </summary>
        public static string Progress_Label {
            get {
                return ResourceManager.GetString("Progress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query_Label {
            get {
                return ResourceManager.GetString("Query_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query result.
        /// </summary>
        public static string QueryResultWindowName {
            get {
                return ResourceManager.GetString("QueryResultWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File In Use.
        /// </summary>
        public static string RetryFileInUse_Label {
            get {
                return ResourceManager.GetString("RetryFileInUse_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is opened by another application and cannot be opened. Please close the external application and try again..
        /// </summary>
        public static string RetryFileInUse_Message {
            get {
                return ResourceManager.GetString("RetryFileInUse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as View ....
        /// </summary>
        public static string SaveAsView_Label {
            get {
                return ResourceManager.GetString("SaveAsView_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Changes.
        /// </summary>
        public static string SavingChanges_Label {
            get {
                return ResourceManager.GetString("SavingChanges_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} items selected .
        /// </summary>
        public static string SelectedItemCount_Label {
            get {
                return ResourceManager.GetString("SelectedItemCount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Label {
            get {
                return ResourceManager.GetString("Settings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access.
        /// </summary>
        public static string UnauthorizedAccess_Label {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to access: {0}.
        /// </summary>
        public static string UnauthorizedAccess_Message {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Version_Label {
            get {
                return ResourceManager.GetString("Version_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View_Label {
            get {
                return ResourceManager.GetString("View_Label", resourceCulture);
            }
        }
    }
}
